# Change these first
owner: pysio2007 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Pysio's Home
    url: https://www.pysio.online/sitemap.xml
  - name: Pysio Home Files
    url: https://files.pysio.online/files/Pysio-Imges/20241005215409.png
  - name: Blog Api
    url: https://blogapi.pysio.online/
  - name: Bitwarden
    url: https://bitwarden.pysio.online/
  - name: Random Image Api
    url: https://blogapi.pysio.online/random_image
  - name: DoH (China)
    url: https://doh.pysio.online/
  - name: DoH (Global)
    url: https://dohk.pysio.online/
  - name: Pysio-HomeLab
    check: "tcp-ping"
    url: home.pysio.online
    port: 8006
  - name: Pysio-SG-DN42
    check: "tcp-ping"
    url: dn42.pysio.online
    port: 8000
  - name: Pysio-IPV6-BGP
    check: "tcp-ping"
    url: bgp.pysio.online
    port: 8000
  - name: Pysio-Home-BGP
    check: "tcp-ping"
    url: home.pysio.online
    port: 8000
  - name: Cat Blog
    url: https://blog.starair.ltd/
    assignees:
      - stuffed-cat
  - name: Cat RandomAPI
    url: https://api.starair.ltd/randomImage?requestType=redirect
    assignees:
      - stuffed-cat
      
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pysio.online
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pysio Upptime
  introTitle: "Pysio Status "
  introMessage: 基于 Upptime [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
