# Change these first
owner: pysio2007 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Pysio's Home
    url: https://www.pysio.online/
  - name: Pysio Home Files
    url: https://files.pysio.online/93AtHome/centerStatistics
  - name: Blog Api
    url: https://blogapi.pysio.online/
  - name: Random Image Api
    url: https://randomimg.pysio.online/output/123871517_p0_master1200.webp

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.pysio.online
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Pysio Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
